version: "3.9"
services:
    database:
        image: mysql:8.0.25
        command: --default-authentication-plugin=mysql_native_password
        working_dir: /app
        env_file:
            - ./docker/database/.env
        ports:
            - 3306:3306
        depends_on:
            - php
        volumes:
          - /docker/volumes/db/mysql:/var/lib/mysql
        networks:
          projectname:
            aliases:
              - db.projectname
  
    webserver:
      image: nginx:alpine
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - 8000:8000
      networks:
        projectname:

    php:
      build: docker/php
      working_dir: /app
      volumes:
        - .:/app
      networks:
        projectname:

volumes:
  database:

networks:
  projectname:
